#!/bin/bash
# Install protobuf compiler
apt-get update && apt-get install -y protobuf-compiler

# Generate the pb2 file
protoc --python_out=. like_count.proto

# Install Python dependencies
pip install -r requirements.txt